### ISSUE TITLE
Roadmap / Todo / Ideas

### ISSUE THREAD

**Issue by dimitre** [dimitre/ofbuild#1]
# Todo
- [x] git clone
- [x] local addons
- [ ] parse options - invoke xcode directly
- [ ] parse options - ofbuild clean  - clean builder folder
- [ ] just git pull already cloned addons
- [ ] ability of git branches
- [ ] ability of git tags
- [ ] ability of git commits
- [x] release via github actions
- [x] homebrew installation 
- [ ] homebrew update via github actions release

# Soon
- [ ] test compiling in other platforms [Ubuntu, Windows]
- [ ] compile universal, arm64, arm64e, x86_64
